### ISSUE TITLE
Faucet (CLI & frontend)

### ISSUE THREAD

**Issue by qizhou** [ethstorage/pm#155]

**Comment by ping-ke** [comment]
There are a few things to determine:
1. How many tokens should be given each time, and how should the rate limit be designed?
    -  0.05 ETH each day (sepolia)
    - 1 ETH each day (holesky)
    - 1 SUI each minute
    - galileo: (10 W3Qs / 1 day; 25 W3Qs / 3 days; 62.5 W3Qs / 9 days)
2. What are the application conditions?
   - sepolia: A user's wallet must hold at least 0.01 ETH on Ethereum Mainnet to use the EVM faucets. 
   - [google cloud web3](https://cloud.google.com/application/web3/faucet/ethereum/sepolia): No 
   - use twitter or facebook?
3. Where is the UI deployed?
   - deploy to web3q.io
   - deploy to our machine and use domain name point to it

**Comment by qzhodl** [comment]
We had one on the alpha testnet: https://swc-faucet.eth.sep.w3link.io/, and I think we just need to deploy a similar one on the new Beta testnet
